[book]
authors = ["flat35hd99"]
language = "en"
multilingual = false
src = "src"
title = "分子動力学 Step by Step"

[output.html]
mathjax-support = true
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/flat35hd99/md_stepbystep"
site-url = "/md_stepbystep/"
